version: '3.1'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-home:/var/lib/mysql
    container_name: capybara_db

  flask_app:
    build: .
    env_file:
      - .env
    container_name: capybara_clicker
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./capybara_clicker:/app/capybara_clicker

volumes:
  mysql-home:
    external: false