"""Initial migration

Revision ID: b6b4c4c1d007
Revises:
Create Date: 2025-04-07 17:20:05.739895

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6b4c4c1d007"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "click_counter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("click_counter")
    # ### end Alembic commands ###
